apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
spec:
  interval: 10m
  chart:
    spec:
      chart: kgateway-crds
      sourceRef:
        kind: HelmRepository
        name: kgateway
      interval: 5m
      version:  "v2.1.2"
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace