apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
spec:
  interval: 10m
  chart:
    spec:
      chart: kgateway
      version: 
      sourceRef:
        kind: HelmRepository
        name: kgateway
      interval: 5m
  dependsOn:
    - name: kgateway-crds