{
 "title": "Infrastructure Health Overview",
 "tags": [
  "infrastructure",
  "mobile",
  "health"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proxmox Host (virtuaxi)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 1, "w": 4, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_up{id=\"node/virtuaxi\"}"
    }
   ]
  },
  {
   "title": "k8s Control Plane",
   "type": "stat",
   "gridPos": { "x": 4, "y": 1, "w": 4, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{machine_name=\"controlplane-82md\",job=\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "k8s Node01",
   "type": "stat",
   "gridPos": { "x": 8, "y": 1, "w": 4, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{machine_name=\"node01-82nm\",job=\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "Media Center",
   "type": "stat",
   "gridPos": { "x": 12, "y": 1, "w": 4, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{machine_name=\"media-center\"}"
    }
   ]
  },
  {
   "title": "XPS Notebook",
   "type": "stat",
   "gridPos": { "x": 16, "y": 1, "w": 4, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{machine_name=\"xps-notebook\"}"
    }
   ]
  },
  {
   "title": "Nextcloud (VM)",
   "type": "stat",
   "gridPos": { "x": 20, "y": 1, "w": 4, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_up{id=\"qemu/101\"}"
    }
   ]
  },
  {
   "title": "Home Assistant (VM)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 4, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_up{id=\"qemu/102\"}"
    }
   ]
  },
  {
   "title": "ZimaOS (VM)",
   "type": "stat",
   "gridPos": { "x": 4, "y": 4, "w": 4, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_up{id=\"qemu/103\"}"
    }
   ]
  },
  {
   "title": "bind9 (LXC)",
   "type": "stat",
   "gridPos": { "x": 8, "y": 4, "w": 4, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_up{id=\"lxc/100\"}"
    }
   ]
  },
  {
   "title": "pihole (LXC)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 4, "w": 4, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_up{id=\"lxc/104\"}"
    }
   ]
  },
  {
   "title": "TrueNAS",
   "type": "stat",
   "gridPos": { "x": 16, "y": 4, "w": 4, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - graphite_last_processed_timestamp_seconds{job=\"graphite-exporter\"}) < bool 90"
    }
   ]
  },
  { "title": "CPU & Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Proxmox Host (virtuaxi)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{id=\"node/virtuaxi\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "pve_memory_usage_bytes{id=\"node/virtuaxi\"} / pve_memory_size_bytes{id=\"node/virtuaxi\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "k8s Control Plane",
   "type": "stat",
   "gridPos": { "x": 4, "y": 8, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",machine_name=\"controlplane-82md\"}[5m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{machine_name=\"controlplane-82md\"} / node_memory_MemTotal_bytes{machine_name=\"controlplane-82md\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "k8s Node01",
   "type": "stat",
   "gridPos": { "x": 8, "y": 8, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",machine_name=\"node01-82nm\"}[5m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{machine_name=\"node01-82nm\"} / node_memory_MemTotal_bytes{machine_name=\"node01-82nm\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Media Center",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",machine_name=\"media-center\"}[5m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{machine_name=\"media-center\"} / node_memory_MemTotal_bytes{machine_name=\"media-center\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "XPS Notebook",
   "type": "stat",
   "gridPos": { "x": 16, "y": 8, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",machine_name=\"xps-notebook\"}[5m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{machine_name=\"xps-notebook\"} / node_memory_MemTotal_bytes{machine_name=\"xps-notebook\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Nextcloud (VM)",
   "type": "stat",
   "gridPos": { "x": 20, "y": 8, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{id=\"qemu/101\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "pve_memory_usage_bytes{id=\"qemu/101\"} / pve_memory_size_bytes{id=\"qemu/101\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Home Assistant (VM)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 12, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{id=\"qemu/102\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "pve_memory_usage_bytes{id=\"qemu/102\"} / pve_memory_size_bytes{id=\"qemu/102\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "ZimaOS (VM)",
   "type": "stat",
   "gridPos": { "x": 4, "y": 12, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{id=\"qemu/103\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "pve_memory_usage_bytes{id=\"qemu/103\"} / pve_memory_size_bytes{id=\"qemu/103\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "bind9 (LXC)",
   "type": "stat",
   "gridPos": { "x": 8, "y": 12, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{id=\"lxc/100\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "pve_memory_usage_bytes{id=\"lxc/100\"} / pve_memory_size_bytes{id=\"lxc/100\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "pihole (LXC)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 12, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{id=\"lxc/104\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "pve_memory_usage_bytes{id=\"lxc/104\"} / pve_memory_size_bytes{id=\"lxc/104\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Proxmox Host (virtuaxi)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 17, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"node/virtuaxi\"} / pve_disk_size_bytes{id=\"node/virtuaxi\"}"
    }
   ]
  },
  {
   "title": "k8s Control Plane",
   "type": "stat",
   "gridPos": { "x": 4, "y": 17, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{machine_name=\"controlplane-82md\",mountpoint=\"/\"} / node_filesystem_size_bytes{machine_name=\"controlplane-82md\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "k8s Node01",
   "type": "stat",
   "gridPos": { "x": 8, "y": 17, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{machine_name=\"node01-82nm\",mountpoint=\"/\"} / node_filesystem_size_bytes{machine_name=\"node01-82nm\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Media Center",
   "type": "stat",
   "gridPos": { "x": 12, "y": 17, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{machine_name=\"media-center\",mountpoint=\"/\"} / node_filesystem_size_bytes{machine_name=\"media-center\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "XPS Notebook",
   "type": "stat",
   "gridPos": { "x": 16, "y": 17, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{machine_name=\"xps-notebook\",mountpoint=\"/\"} / node_filesystem_size_bytes{machine_name=\"xps-notebook\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Nextcloud (VM)",
   "type": "stat",
   "gridPos": { "x": 20, "y": 17, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"qemu/101\"} / pve_disk_size_bytes{id=\"qemu/101\"}"
    }
   ]
  },
  {
   "title": "Home Assistant (VM)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 20, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"qemu/102\"} / pve_disk_size_bytes{id=\"qemu/102\"}"
    }
   ]
  },
  {
   "title": "ZimaOS (VM)",
   "type": "stat",
   "gridPos": { "x": 4, "y": 20, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"qemu/103\"} / pve_disk_size_bytes{id=\"qemu/103\"}"
    }
   ]
  },
  {
   "title": "bind9 (LXC)",
   "type": "stat",
   "gridPos": { "x": 8, "y": 20, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"lxc/100\"} / pve_disk_size_bytes{id=\"lxc/100\"}"
    }
   ]
  },
  {
   "title": "pihole (LXC)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 20, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"lxc/104\"} / pve_disk_size_bytes{id=\"lxc/104\"}"
    }
   ]
  }
 ]
}