apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-alloy
spec:
  timeout: 15m
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana-alloy
  interval: 24h
  releaseName: grafana-monitoring
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
  # https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml
    cluster:
      name:  ${CLUSTER}
    clusterEvents:
      enabled: true
      labelsToKeep: ["level","namespace","node","source"]
    clusterMetrics:
      opencost:
        enabled: false
      kubelet:
        enabled: false
      node-exporter:
        enabled: false
    alloy-logs:
      enabled: true
    alloy-singleton:
      enabled: true
    alloy-metrics:
      enblaed: false
    nodeLogs:
      enabled: true
      labelsToKeep: ["instance","level","name","unit","service_name","source"]
      journal:
        units:
          - kubelet.service
          - containerd.service
    destinations:
      - name: loki-grafana-cloud
        type: loki
        url: https://logs-prod-024.grafana.net/loki/api/v1/push
        auth:
          type: basic
          secret:
            create: false
            name: access-policy-password
            key: password
    podLogs:
      enabled: true
      staticLabels:
        log_source: "kubility"
        source: "pods"
      extraDiscoveryRules: |-
          rule {
            target_label = "log_source"
            replacement = "kim7s"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_controller_name"]
            regex         = "([0-9a-z-.]+?)(-[0-9a-f]{8,10})?"
            target_label  = "__tmp_controller_name"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name", "__meta_kubernetes_pod_label_app", "__tmp_controller_name", "__meta_kubernetes_pod_name"]
            regex         = "^;*([^;]+)(;.*)?$"
            target_label  = "app"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_instance", "__meta_kubernetes_pod_label_instance"]
            regex         = "^;*([^;]+)(;.*)?$"
            target_label  = "instance"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_node_name"]
            target_label  = "node_name"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_container_image"]
            target_label  = "image"
          }
      labelsToKeep:
      - app
      - cluster
      - container
      - flags
      - image
      - log_source
      - namespace
      - node_name
      - pod
      - stream
      - instance
      - source
    selfReporting:
      enabled: true             