apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: "=2.17.3"
      # https://github.com/bitnami-labs/sealed-secrets/releases
  interval: 24h
  releaseName: sealed-secrets-controller
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml
  values:
    metrics:
      serviceMonitor:
        enabled: false
        namespace: sealed-secrets
