---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: db-secrets
spec:
  encryptedData:
    DB_PASSWORD: AgCBeib3Ex8xlNsxrrZYwfHVOT+DuAzz4FUMu81/mjJUQrcUcSsWnV4s/a99QIqNVl5lL+62rzycMBm8y+92umbwXrZsdTbTHDkSU6bk1QCE+2VOmOa0rtmGntwqgp+ifSkMRze/i4qmufLj6i7rmi+6kG/8WD9Brka0YUDrAdnDtn5Aco5chd53dc44at1twkQ1NG39IFI830IQl3f5n3USSPrn1MnwUHuoRz035jqxeRsa3FrnfnVRtInM+KGIQiCgJoTiZzJZ+NeRIbLLHSUI6X6SjrjhUqiF0hhaBIQGxIrJMDfcncWREnND2Mn5y9kgDw9Wr9mlYfObI4Up/DqIU59liKlNTJnyUbxusfWFxOasGq0v/AeFlkvLKVT1OA7E4j8NjhYEsMgff107ETzWL3/qmyBo1mCZrmp9M9xi1DrJ2jUAqQbNlCRvRSGiG8Sj7y5BnVNyTqZaZFjDmLXhZqP+9kjIxS8xHZQXerLjvTBmvWlAVfw7CS3l/rtV1N5kdZjsH/ek3E0BVzxz1l2yg789t0vN6y1NY9vcULveahf1EpqyBA34dX4Eu1P7StBkA0DQtZJcCV8Iwt2LDQ4s/d8fad2WZoXC4tMIZ6LkO1CbB0Wh4biU6a1Rwqq6KNIiJ+SRKQmMrxoEYX2OWiHKb9sil76dSfdZmPZrNSIeF5UkPlbBc3RzJiGueOSxrYC6Lj8YLJ8Yn1MS43fzElo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: db-secrets
