apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http-gateway
  annotations:
    io.cilium.gateway/service-type: "NodePort"
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80       # Internally uses NodePort (e.g., 31000)