apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-gateway
spec:
  gatewayClassName: kgateway
  listeners:
    - name: http
      protocol: HTTP
      hostname: "*.internal.kim.tec.br"
      port: 80 # Internally uses NodePort (e.g., 31000)
      allowedRoutes: # Add this block
        namespaces:
          from: All # Allows any namespace
