---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: vpn
spec:
  encryptedData:
    client_id: AgCjexjtOwTCMoJG1xSJZzCTMUimFTdqeu/u7z6NFarsizZMH950Y9UKoxLwhsQe35/Fw+29RdAre9BzJliOKaN9dW9m22sRcbo1rWSRwxcxXSJ2IuYBu5PGnbJ5EKqpf8DDefhBr/RPkmmS10Xs70hpMlyp6arpqmWRCyrVaf20yfh1SYAmbiz39X1Bj5mjLuf+7LCZDFuzHrQXDgx1cEe44U+kQC2szfBo9ApkkWYN5+dLFWdVEXgiYdGJPl8CnZ390FNeNobFDViPqKHrnqFRIuief4sxPDJjVnFGQHyaEw9Yyygx3a/+Qa54RETXiigfa8+b2IDK65gLLM2zH2O8Ymo8BiH2yqdCqI96f2JIIA0tsBQLxZFl4N6iadpMxnO8JlHo0GoyfLxQtO/8itReUGD3aLTUAoCz05yf6k9GX2OIyPewKsHEHCKG15XiD+ywEcg817QtTFvndGNcmri1MapiMfyCtl768qeemhzkmpy5JF+3i6E3cu6V0KOQn5Z73N6DhFH2wttf25XJWo6n66wbayCDQedzhLISNzsdotwZ2pU1EE4g228phEh95CbF78fl5Ec87vTSr6YqgCzdNmvnHB3k80zqW13fby2bGUrPnvIHVDqLhdLb+lAKN4GJDwjq6kwD2Pn6Z1que85yN5CxXTrF1Iao3dgZcCA0N+ADbvkfGbpYKwKZ4Jq13y4Mf2Guhrm3bK9WoJyB3Y0PQg==
    client_secret: AgC8A7SYLKPZnPHwahzf0N8GDX0C+ko0cHEPLwHw/QD+94gFhKMeM675LEolKJzWNYOO1Q3lVTP/JD72n3XlHq7ded2fIIDfn/wI9fmLUW0Zu3Inh87+mNRLpeaBNmd3rd9FkTUIWENAVzJD8S+acRtxbL4VFxUq9BGOGO5iiq5U8eoDgCkZZewwbwUGVkeeoArhDGXgi4/8gmgiGdCli5CrmA/AEHp7U/7Y68moEiwsyJMm7/DX9CiqCUnbFcAzwisII+KuwqBYr0Mx9J/QsJoCGRqnkeOrcrfzMkCvDugBK82i3TZZXiRXcwz1d4xkD3zs9BAiqsFfwMjCqsK8wVXJodZIrXn8++6xN9n8gcLI09+jt9IYCdeREafJ3vq1Js5qICpxEXUy/ZCuojK4i5J05E/lwjbIKTAV2+63OIZBShDs3ixnxuhFBlQdMFeQbHNCMbqoLpBjhsEKAbVZjmBge/iuoF+zDQrhrrL/dK8lRu+ABSs17AlXpnC4laQD2nwcocKnyf46RmQEIAt0WtULN3YDG+GF1z9iBeS3fvJkHlLklPWCh2k2xnULvkyc6qX5GNlCIEgCFY0hacERgJcmD9CQpLLj4/BubF5Gz8N8w7IWleBNSjrxz5hmFbIkNH//7/Y5R2x4cn21Z0NLmahfQBqYOr/CIB0QQFkCjyA56m+TwAKqJ/6+wZN0W8eNh7Z89e2dn29hN7m3ACK4hCsyr6Ull4ORSSIwFTUuPL83wr1oi0BCx6sID8TEwpiDbhY5tAztSr++qi5siPRHsHQ=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: vpn
