resources:
  - ../../../../base/metube
  - pv.yaml
  - httproute.yaml
  - pv-nfs.yaml
patches:
  - path: deployment.patch.yaml

configMapGenerator:
  - name: metube-properties
    envs:
      - properties.env
