apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-nfs-pvc
spec:
  storageClassName: nfs-csi    # Uses dynamic provisioner
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
