---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pve-exporter-secrets
  namespace: observability
spec:
  encryptedData:
    pve.yml: AgANJk20HDPg78DFeNPLmPhDyV6jRIPwkEWVkBdVc/GZSwZzidZ+48uSIzuYLq6dbFPJdCgOivivQnjzjvO1kYumQeHW3c7T6bYh62HQeVZZjBFtS1UA9/zrCi2QZFL4miEKMeOi29/9Y32bfZRgm2hTHWfEZWzzSZYLxyVHQaMHqGRaxIm2uHL7+trSPS/aqyW9QDusycfnOznuPaDRnvn2awPOqdfAB640KQW3G/hjTDYXnZc74r8WCL7RBUQEmxtc09gd3Lp2IKQPlbMCNy1+qTOeUMhBs8FoFPryHU+udWQdhm+i2m5qvrebaheIC43pmhjI2IX5bgumcrsYNyk+nTf8G4AP5PHpFlomI/KK97zUXNVAaXoBMjZmE5RsJmGChkTbPf3YPdHkEifc7Dt86CHt1f4g0mBNabb0lanatvRbk/ml15TJBLKb6Sl/WVcrVmpP2aDz4AhFZ9DPbOgLI2aGIvnEXtYgDkYW1fnz+fHea0iRJ8OEp583OLKqSDUBOVBnqA2f0dDUks2TgfcWIXUgdZwEQVlFjHsOFmdq0G+VWDgTBp4AiQLzAiiWagSS2eU3YMy19gR9fXMbsvWV5xHcjNOpK0vZD+ZHtIIgJrJz1aIco3vi4I/sSgcV8qecta6qkuMLm326QMo56Sw38lzpq2C2r2Y7928lu1zOpgRBLicZ4f7ResWghtdrPGwuP8+EBa/fMVJLArtdVRNv5/A4znmA8ZTbvNfYlAI93on1odTH00NHP1iSJUWZrVrwMhFQpxkdm7RsxfcdA/UXD93Hdj57/Z77iR32+Yl1fZ8z9bnrt9WoJ32pIdeEPUZJCPguwxG4ZgeREwo4kjQL+DyiG08qGgK42h+iWthtKPAOfd79
  template:
    metadata:
      creationTimestamp: null
      name: pve-exporter-secrets
      namespace: observability
