---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pve-exporter-secrets
  namespace: observability
spec:
  encryptedData:
    pve.yml: AgAhq2Xs4ECZfG7LKPolphMeTb0LLW6Skx7MMlP49CO1FSyoGybnsJ4sWMlesG/tKj6TRjlrbXobwQSD0Cap0lUFAgqZoTz+M2Y1+uUz5aX12A5TWy842jmQD/zXCJtTF/Vfpm13ztiJ7COy0WQw6ut+9EXnG0I2UaxwuUFyvO+JbfKuiTmJDIWoRrrbSi/fJy/ZcG/QzkVm5g3nT9rA4zRGuvsEFi0gVLO5ShSjY/VvTd6lh3UlzAVAuIjY1/onkAASkakDv2tRJ03w+sZS5N2vHmBW8iJunz1sVDCjEv/amC/+Eu6K3XnOU40fpAa77uoAD2OKueQM0J286Pd21molq4mBeZelmfyqhoE4UBIXWQyDhBeCvNsb1b7icP3BTviIQozasez6Li9kiGGr4f2FSCY8gqqtN2x5EEef3zxeDGqXrzRG2Oqm9wVroA91XHjwm9b8EoW90k0/Q10FKLXOpVA2D40lBZ6Sn5uoFdKUAizfLamMyCtFqhgQsCR/NXajrHWC+R96fGaJA9XFuiMu9QqHAS1E3s8jn6qelLbkF1FrtZR2VLGxbHMxXGtESjjACx5dOC4+Ewx8JeX0LLR/spThVTyvzl+wPrGbE27+O13rQ3BLMGzoB2hCBPnfxzp50WBUmNzBqrB7AFK7Is7non+wYQITWhY43eH9Ng+lEGjfg4W99TROJ7EnQahZOronmYgUVbb2LCcnL9kUaHP1SKt9ytdzSQmNcE5Y3r9SQxXg70NU7itmZb2TB7RBMPpdRtt1Zb0rKjCR0rn+l3nXK8AnMyjTn7CM89x7kyHMyiaNd5f2yNFNnw2rZkvp2jUn1zNAr/gPzINSiJ2e9rqMoAW/Gge7yhesGaBBb/WzyBo7VmZ6
  template:
    metadata:
      creationTimestamp: null
      name: pve-exporter-secrets
      namespace: observability
