apiVersion: v1
kind: Service
metadata:
  name: acme-dns
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local # Preserva o IP de origem (importante para DNS)
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: api
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: acme-dns
