apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- httproute.yaml

configMapGenerator:
- files:
  - index.html=html/index.html
  name: mari-site-html-root
- files:
  - logo-diamante.html=html/logo-diamante.html
  name: mari-site-html-diamante
- files:
  - logo-normal.html=html/logo-normal.html
  name: mari-site-html-normal
- files:
  - nginx.conf=configuration/nginx.conf
  name: mari-site-nginx-config

labels:
- includeSelectors: true
  pairs:
    app: mari-site
    version: v1.0.0
