options {
    directory "/var/cache/bind";
    recursion yes;
    forwarders {
        189.28.176.25;
        1.1.1.1;
    };
    allow-query { any; };
};

zone "internal.kim.tec.br" IN {
    type master;
    file "/etc/bind/internal-kim-tec-br.zone";
};
