---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: observability
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAOANFFJWDP6hQFoz9QWYri90pxnAQVZp5KgTYWg6ldC/HvrDo8eWA9Enn40wH94+Meb66WNISr8OealL/ge4mznxHU4wPPPCk4DBFrA8CXmf6mlz43FLMvdwglfa/MwKMygscZh230tqD5dXnKVXDbAmRUUdHNVqHCt8UdNmJmeiT2qRJ7hx93riGwp78AGXr3XFFYGwwIEZAFQpqdA0owH14WyzfypP4oIGxb4fteZR/2/89H4fCQT3p05WJWECRyKV6LngwKJQcS2ICmtzdPcDTu9GqMBUWdMmLTyIaX/5yvJwS042nxdC1zuGB8bsJs7KolLOzlwAv58Js+BBeB6aMxPs5DZx/h9KYy6UVBwknv11wIaqcs36fGujrUdJjLlKZpSBHHA587x4qD2z7VO3kwsIPPyp7MS7rjadqL+KxCarS2i+/99FJPzuCAcrswrDB/LMZjgNkjPsVnFdW3slnWJMYjAKyOFNAKYdMgDM/ULdG7DmJCcw0TDlp0l8usc55raXVnWE5gty1iVb6MS9jebT2bIi46LNMVhXObGmueqPfFTAOenhnCwBv6GF0u8llKJW0EttaW8QczsN15fAtDg3J6CBp6ofLjt7qWlA2AikCPOTarFOIJ1YAM8VIzTSCqYBP87F+jOCC3mda7+G/jAZxwLx229wqORq89p96WhxmuT3YmiWQFFMP5DtN6RphUCHkq6rcaH6ILejDqGgd/Ww==
    GF_SECURITY_ADMIN_USER: AgCeLfmeUUJJzIJunzuOnrc5AcLkms+s1c/7bVABbdLPWJOQZX4YVcylwRyMGZgSxV7Q8ALxDHZtjxpo+SMSqNbo5DupOhCKtQstK8kK2uvCVZ1darlMrTyYE6+IfPuVcahLoniySofPXj1WJjfLvyPIrvKxiq02nzs6rRzsKUulKMjXfspv5448JMO1BbUIxIgyaQDfVMH4CaGcOt0Fo6kA1g7EXb78/AUB8XHeFQ4BFd6p7r+lniMnkOhGyV+dRzNFJJuGnJQ/x7U33TWCn2YD6+z9VZkNaJIxHmisUo0si98FLPKyopIMWiBHcPVimVu2l2oC/MOdsiAWxFWYiKMsfsz6YXXSnjxz3GMnTKHzEnnxt0kdTETjgRBxgDOX4uMHHi6UCnSwgJmqF/Mp292QzUAZwJ/jzodwVRsrRVV0k1SLRxqJbkaadyOzkIITzRrSvOz1FgMCH9kBDuFtjdWqi6VNap/fracDGYs5Rvl1uW3Tj/fcpHWLxNl8bcsyfW1omb4vJq7HQy9o4pC1OujSkGnTU1DRqv1A/vucsnPbMKhnRdukWDMONE9cU731+NHjfMCC3Uwb56YZRYAMnAOtI1tChw+1CEGhVu8IEM9mDE4gwmncP83/u5akDCRkCiKU9QTU58aDh7dkQK2Is/RqxS2nJEaCajOJ5puBljnDcb4FeUU3ctrFy5sfR38CufQKQBnxVg==
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: observability
