apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: faulty-thingy-route
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: faulty-thingy-route
  timeouts:
    request: 140s
    streamIdle: 140s
