---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: acme-dns-account
  namespace: cert-manager
spec:
  encryptedData:
    acmedns.json: AgBkR/bcwhHXW2vtJNJDpTBBqsLB8UwDDZvPNkFcMT29PaKR/QDdhbB3fvKC00eRsDHYyJTDUtg3FlCgNOJZ4JNhkEkqLuR0krkWdhH2D27QvIpZDimVRYqVA7tgtxuxZSLws8TwSA1B+EFPJF/pMtMLCeoV+OgTJksOmNgjrIlK9rOLidFuiYX7TZu6ak4EGSzdXKZhoV7DpZgVwEXNQcr+HjRMj+UHwVErmifMEa9phoU1YXfyKIoaX9zt3Dp4sgNvjRhIH1tPov49n37D5gXdalgCkBUiLKaGhmyTlKAyZgbmnZFLa7pTzeQ/6nw1tSnIzn7VpL5Syp65lEDO3GPiz8ZKMeTpgLdicJRV/juaqHJvLDWF4C7KytZ8rVZIWkenCynzDFfyajcYp5OtubExtW40wWUblypPTry/SnMntU+XcIazrgG4mM6eGtTExr9EjdW53EsUiWDA9hrPDD7QqUjWyGWzvCzIJdmEeaq9hXsgJsAr5qxBSrBZUwl4vjvdHuvlV8hLOQLP/cxQ8SJmP3kmiALO/pS1CEVFkCLhI47giQWneeQb2RCgMYEa3ln4t4YmTjDBShtiIw7urVwDYrj6mQ0mlqaj+HOOMgIInTiZaGIeQtr2iNSSe7YWk0fPB5ieUgn+ftNFBHz1Y1Ww6CnSiC3+cOaewvIxEhj08FjLUjrq/71rPuz18uGMXO/QfPWfHK6Pn7EIh6MDodgY4nNFRxVdKUFLGl/kANQWxMQZZrq+SpDjujKjDZqUanmfjBYLNyNh8Qubf5m9PlvlEsc2J+5QS1eBCrsaD1BMS4Mv8+clfV7Cs2p2IycQUUwBXw3Ug2cbzisQronhmClCLpExwPrYCrxNdwpB1ZU2h9qiQqhupWuy+N9ACL/fyPDGerT13dnGH7ruDSltB54l/4yyOz7AQtjNoQotDZSwU7CkTxKpqCKHy1LCysaDsu7qmzUh667IMxldhxq5mWvxkOevnY/8LcJ/1athkrA0SIepSoFivKhKzc/UmeDS99WAJf0q
  template:
    metadata:
      creationTimestamp: null
      name: acme-dns-account
      namespace: cert-manager
