---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: acme-dns-account
  namespace: cert-manager
spec:
  encryptedData:
    acmedns.json: AgDLtZwQs1m0naoohpke7d1za+LUMpCp2pCMt98G3MnkYOt7PdQIyBbK6XortGGLlClmSWdSLX0uimiORRRvq9D7iaMX3fSIDXljk/+cgTK6KefltPZ7K7/9d5nMFQMbEPYKdkZ85zFLFzvdIM/ZUVE+RGEcc6p85HlsVWagUa0/eWw9O2Un9Cem54HR4zQR2BYhLPnRke4RaopTGSBAe0Oz08CiUwI2S+7Cs6JKjUdoi2TbfSuf8ENutPfpqQT3Vb7JE3MtwW5Na+daB84vG/ImGPYXyxae0YwNQDeVr8ZnoAeg/1POL7kd1RwiGkfxPtckPBDX5WxtCfrC24W/ukwOiqtIP2ZhSQkug/U0C/JDFtGn68irAKX2S1NWk5YqolQO/26MtiMJCIZSBYQp0MBjFxrXoram0my3kTIIIg7QQMqRRi2SFXYP2IsHaJhgJtF5L7dvMnG9/5MmpM6yJH7EGMhyNjvFpFzkjmivB9PSWibLO4ZFWoKFTW7915OWYI0Zg0zibMycHbjuQq1ZhmoO06+s4z4gf4z/nUuN5UO01pe2LoaBSsLbSwKg/4DoVQd2+Ur+C1AaSvSxfhBUSat29Yw/PgO2GH93i9W89OzFWdtcnVystYxH1+2/ELxgv0PpiDxaryb8S3y8CuR/6Wq2Tjaq90XZ4TQr5ujJDTVr8rHwnKe8CDslgbqWea62NJPU2OYOYkZAqGAgiaVj/0O7n3MBzuZ4eom+GW18kM8qtg2FNL6gWNNfs+uXvtuLQsYEd/n06WrmUByDLWxv4G32jz7saqvKf8cJP7BE3WWnF8LXO2ZBaIvJtfG/3qBa0w+XQIVr6XarEFUH0G6XAHCsKDWopgIvO1oVCESkDonBtmizeNP43YHwtTa/Q/ZpvnRh5eJfCauPPj9GHGI3+m3sXAUEh6GHNfPcER9HuHBHd6bofdJ7JHPdr9GoMc33CnpsWKLBtaXvZ/MvWdndqRlVZcK8nWv3ySa/1eo90Zc+YSQlWghJxYyTPKzgEak6Dj476BswTyqlMbGaKfX/fJIYU2ToLPAsm++rvLCzCnxjqVl1iQcfH3AKIYk07UJckRh9hyxfGUQUyGo8OO6HbjhFo7b/mck9fdMwYFXDxfmsddU=
  template:
    metadata:
      creationTimestamp: null
      name: acme-dns-account
      namespace: cert-manager
