---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDdT8N9GiTZofLgcxzjw2R4IYLAMdykPdlWCAtiWAsH0frzLXT7umOU1yLdJhi438xKvNtVwzhaZ2hoNDPwBnEsPNdhACzlwwLOpLpDqzaEpg0WAYrhHNe9yXkilmp5efJuCRV+7t012a6hBkcqySWF8jrPfkrkqjFIbhqv6RPsi/DpSq4qjZOMl3Gc6NNSjWat5pZutEpNzVLZkxGfjkSMuyOhr9UYZ0nLfiEMtLB8JNDsB7blrmIf1JF95RAf90rxe5t41Naq+REuNVswmpnT+AWGQfAEmgUUKy82yfrdnm5HYegrF8PNSovVKXWPohLC99a0jmdQOHHhOIjv6xWTyZD1ZQmoll7IxEvBKHZd78rXCK8stmLRbVFFoW8UD9Cs1LE5R6ITTv2I2mGM2r6KeGnOtYphD5zYE3BSMhH9kQQIe4P+MNrLQpdqm6Lt3XRjlUShg++nHseIpuIaFq7sn7vr5L29o1mBjQHAMGzWWMeZwNTW1+n6UykLHL0nANJWzTum9ZlPXkjbNO3embDmhLoAmJJNYQkHFYmfMes6BpM5FeOWAu7NzqQMD+9jNU8ncN+BIvuqndBEl0i96UWGWqMNFX9ag884w+ExMOxJrlatwYAHGico3GUssNQV/OweZ0m2Vf7lvaRrMAbmHT5asQRCALkAKSdSznEdf+VLtfG3eFSkYOElHkyGs9zBBPBl3cbxp8JP53Z4pZx+ecc5+l9tNXLNyKseyyVu1fI8tmwu/uQsuSmVD8ujY76GA3khNX3qQA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
