apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kim-iplinkdns-com-cert
spec:
  clusterIssuerRef:
    name: cluster-issuer
  dnsNames:
  - "kim.tplinkdns.com"
  secretName: kim-iplinkdns-com-tls