apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: base-certificate
  namespace: cert-manager
spec:
  interval: 10m
  path: "./overlays/kimawesome/infrastructure/base-certificate"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infrastructure
      namespace: flux-system