resources:
  - version-management
  - tooling
  - steering-k8s
  - dns-server

configMapGenerator:
  - name: coredns-custom
    namespace: kube-system
    options:
      disableNameSuffixHash: true
    files:
      - "kimtec.server=dns-server/config/kimtec.server"
