apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  releaseName: n8n
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: "=2.0.1"
      sourceRef:
        kind: HelmRepository
        name: n8n
  values: {}
