apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: n8n
spec:
  parentRefs:
    - name: internal-gateway
      namespace: kube-system
  hostnames:
    - n8n.internal.kim.tec.br
  rules:
    - backendRefs:
        - name: n8n
          port: 80
