apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kgateway-monitor
  namespace: observability
spec:
  selector:
    matchLabels:
      kgateway: kube-gateway
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - port: "http-monitoring"
    interval: 30s
    path: /metrics
    metricRelabelings:
    - sourceLabels: [envoy_cluster_name]
      regex: 'kube_(.+)_(.+)_(\d+)'
      targetLabel: kube_namespace
      replacement: '$1'
    - sourceLabels: [envoy_cluster_name]
      regex: 'kube_(.+)_(.+)_(\d+)'
      targetLabel: kube_service
      replacement: '$2'
    - sourceLabels: [envoy_cluster_name]
      regex: 'kube_(.+)_(.+)_(\d+)'
      targetLabel: kube_service_port
      replacement: '$3'
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kgateway-app-monitor
  namespace: observability
spec:
  selector:
    matchLabels:
      kgateway: kgateway
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - port: "metrics"
    interval: 30s
    path: /metrics
