---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitea-admin-secret
spec:
  encryptedData:
    password: AgAqbc0wy8/taRErnR3GmT3Kyx1Im3cQ85TC3Yj5fcz7AkPlM5vV3V1UQOFeR+6P0sKWID4hUbvuEajpOY53+YOcfESScWnEPo7WDPP0Fw3cRwg8SiYqGwFLz6QTKJFS0jpZtsq5GiRzvuD2HRI/lG9P4h6vIxh97ZUyvYDAiBnXQATMZFTAjSBsdH5Sqw60JE+9DUuLQ+2vH+V3drjZ02g2Sc+l84hWYRRjX8lbwdIw5Yr1ZQSOq/ebsA7SLNNtMhMu4slahdUePiwC2orPtNinBplfK7i1f24G9ef+R/Yv7TKOmQIH96f/VSIFH9iW1jZuI9zdziomS7yMMzrPp2TVnhoCXcURyZ/ZFKgSDnQPrdn3qii+OpHnUilfrE89LGz+/m39Jt5G1kLoi1mwEmmzxPQNLoU76WlvcJSKabjPJ+dkm081w+7BVkV3MPzHBI+tG+BW713nENwi2MLCR8lpa+lLzNjzS+5PxmAi+Lx1gyUtwBk4HgCY2H26erlbO9yOb88yoxug3FAorjuGlKziztpaP0ufBe/b4SgaXTY7obrp14ctU+PVlUTuAk+qwNIrnueVYcsPhidOnsHduQWqvt6lZIFaBc7N7SOFaSEOBxByUs07PVJ/jYX0VMNH//gUJmszShr5/IDTKRaUO2wMmRWAvbxGrkQ9ZPmjxrZJl92tb5/0/J5uQU+Ahnzhdb5JvKGj9KZnAdU04FRSR0oHj0k1AGO87eI=
    username: AgBQIlhdVVXfXTzYYe+H+7Q8NudJ6OCwfFuQhleZmerGOZvW4JiiZSvUCcylEecDzPx/Ju9YLVFdEyt9WFIIuZIYf2rEXYp6ZNG8p8D1On1e1I1k/L0ihex75Nwqy+zHLYzxYnsfnHLN/M01dUMBoRJ5pXZJUyFXXQobZh6bx5azJ9ig6OXYXHADyFQuZQ3bVgXA50PzrP/NFgwpuAepD9YI+iiib+GFvAnXx9wPEzxOB99gWj/UKYI3riNTZ6y6Gw1uq4+mbuq3eXdz2pdvAwoX9HrxEVVcPnGhVPEwCRl0pYN3G4+ib0P6UrVAAyj9xLLEGHhYBTKs5a1gXsQwET4LT2A+/Z0LUgYVxjsw/VD78bZS4lrNVL+j55ZZki2aRMKF3qT0WwsALuhPsMWQkHpwhySJqxXsuSHn7vGYy4KAgD4MpXXcdaAKocg1J9FXWksKgMDqAMaTnXWWkKqC1buxseUN4Tk262rmVCDo5mV5gr+YezhMKbCLLrm13yGZQarR+8DdbbRX4EnRf0xjYhTanEeZWVW2xo3OJarXbPOdMqz0hsivrwlfZQNHerNzUAqo4qEWwkwvjlDUsTz00bSy4Bt0P1nsH7q4tfqiYBWFtptGg0tAT9OxH0SOZAoaArc/UneOs41c/8cg+9MQTkqxe//hg1m4dw68vwN4WUPbfr2ZgJ7RK3H+6zOhpxyazJQO8NA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gitea-admin-secret
    type: Opaque
