---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitea-db-secret
spec:
  encryptedData:
    password: AgCToPQweI/AQtBNIDTl1ASi0NRHARTCG01Bf3pb1fJ1tWQtZEQs5XWJTObYJC04gIyNMpfDInC6tek4QsUVfs4eElRV9ZnbQqDz/KL2/VN14MTvD5YYmGgTOcx1pCDnAJP+2FHrH7sLStxwzpDbYjWJK8+ej6mUv0MUwu8rNerdkHHcWlEAZWoJAPjrkdYJ2ICeD8Q7+WoZI3SBqP3PM0OOcNb5ovR9nztnySZ3fIbbSSU2LPGAZHucAmF3BItBEzL/gneaCPcefwNBZrPnDKhfoehYg8MH2i5efdcYV5Epd65Sinrsr6SpVqq55TWsH1qJhWe7TwApYw3jFKhRzM+w1M6sHTBA+99z7wY3VrOsM24H6xavLD4vi3KJ08rVZf4RA2JjhsTAwQsXtSpGDDBW3aW5auGVSH/56Fr9PckuVAEmPZVBfezc0OHOni7x3gW47aHr7USb0h8h3Rs9kJA4yav6jff3EFLJinL/AIJwwdmSq762QPZ9bkoaY0Zb2QLuNUk0LS+eh3sHbIjCt/9oD1dSYe/1nVi3hb0agLl9kHwENdb7ksCLfvpzXxULSPO0KnVxKD1kpJkR0ak+GNydRNCOBZnZZmtkptBt8EuhaE/ZjTkPJloR3FFqFQuW1EUhjPU5CafCcqfLsLrDOngD1bZzb+fC3lrliZDUVP9Ef6fYwkyTc5a3s8ecfFlKWpE8CdBnKQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gitea-db-secret
    type: Opaque
