---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitea-valkey-secret
spec:
  encryptedData:
    password: AgBkPh+a+3CeMatg2mHyjtIHSsFxFSsG0arzNdNXZpdZgNirsnZU8EtUzhtYJR/kBvyHvSXalKc/MRb1UE0ZC/dy7Y1dFkg7VMOrrEHGMVUwGp52mRgdytMQcKQKfKPqnT3ZqnBM3m0tuoheFKjKYnwuNiah18oBPhdDnBcz6KFBlWIGYt6/ihhfXQGBqQMfvqoUmeGhnmygUdYnDEbsfLVFZZldwaP0lorBPKChjoCnDHI05pfjadK7Ef+vPuLVzaX6FgSHyAqIawFegPUGuZp/Ak2u81vBy7kRCagBA/w2AgI+yjvfby/eRjrTvjzF2ve7tBxyONgNM3aRe8G5B9o6NanHZKoSVntPgfvGJPk3RioIO1+OJv+acg6k17HnWn8xT1n47Qjn0qF1hlnaX10xmuzejlEAo3kcung6gzK/dttgmlMThuXih9wWTvis9J1+gDecpJLCm69ey4EVRdouwIUTtsZvCl8V8YgAHL57QeD6x8iBNXjTxCpVFP6ePk+Iy9c8zRwukjZZpbFhwOI18KVb2TdlEXRmZx6r6PyYPcQW68QlzSJikuphLziECbLzKgXJMWZVoY6oIxN3LdE5wd4QcrK8rE/GLd0bTcWNO6k3DN+JzFfD+5RtfHAKIRciXVeNN9ze+BmrAhdHDEraq4iuZnGHSiZ7Tav1tjjB3T6ZHzmwYZq8LG9wiXlf9qcWi5PKFmuEKIlsxz14RXTP+ahWmJFWAXYAYo0q9jGZ4Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gitea-valkey-secret
    type: Opaque
